name: Pre-merge Pipeline

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/check.yaml

  build:
    uses: ./.github/workflows/build.yaml
    needs: check

  test:
    uses: ./.github/workflows/test.yaml
    needs: build
